from .utils import get_predefined_templates, get_labelset_from_dataset
from .classifier import PredefinedOvClassifier, LearnableBgOvClassifier
from .clip_surgery_visual import CLIP_surgery_RecWithAttnbiasHead, CLIP_surgery_FeatureExtractor