_BASE_: ./ebseg_b.yaml

MODEL:
  EBSEG:
    CLIP_RESOLUTION: 0.7
    CLIP_MODEL_NAME: "ViT-L-14-336"
    FEATURE_LAST_LAYER_IDX: 18
TEST:
  EVAL_PERIOD: 10000
SOLVER:
  BASE_LR: 0.00008
  IMS_PER_BATCH: 16
  MAX_ITER: 120000
  CHECKPOINT_PERIOD: 10000